import type { BplCategory, BplLevel } from "./bpl";

export interface BplSongEntry {
  title: string;
  difficulty: "A" | "L";
}

export const BPL_SONGS: Record<BplCategory, Record<BplLevel, BplSongEntry[]>> = {
  "NOTES": {
    "8-10": [
      { title: "Pink Rose", difficulty: "A" },
      { title: "Wanna Party?", difficulty: "A" },
      { title: "Digital Radiance", difficulty: "A" },
      { title: "Dreamship", difficulty: "A" },
      { title: "IXION", difficulty: "A" },
      { title: "Journey", difficulty: "A" },
      { title: "Mermaid girl-秋葉工房 MIX-", difficulty: "A" },
      { title: "NΦ CRIME", difficulty: "A" },
      { title: "Sleepless days", difficulty: "A" },
      { title: "wanna be a \"BAD GIRL\" feat. Nana Takahashi", difficulty: "A" },
      { title: "WISE UP!", difficulty: "A" },
      { title: "センチメンタル・サマー", difficulty: "A" },
      { title: "真夜中のバベル", difficulty: "A" },
      { title: "翼", difficulty: "A" },
      { title: "7 Colors", difficulty: "A" },
      { title: "ABSOLUTE", difficulty: "A" },
      { title: "ANEMONE", difficulty: "A" },
      { title: "Ariah", difficulty: "A" },
      { title: "BLUST OF WIND", difficulty: "A" },
      { title: "Chewingood!!!", difficulty: "A" },
      { title: "CUE CUE RESCUE", difficulty: "A" },
      { title: "Daisuke", difficulty: "A" },
      { title: "Dazzlin' Darlin-秋葉工房mix-", difficulty: "A" },
      { title: "Explorer feat. ぷにぷに電機", difficulty: "A" },
      { title: "Express Emotion", difficulty: "A" },
      { title: "FLARE -炎舞- ft.Nana Takahashi", difficulty: "A" },
      { title: "Flash Back 90's", difficulty: "A" },
      { title: "Fly you to the star", difficulty: "A" },
      { title: "GET UP AGAIN", difficulty: "A" },
      { title: "Good Looking", difficulty: "A" },
      { title: "HAPPY☆ANGEL", difficulty: "A" },
      { title: "Harmonia", difficulty: "A" },
      { title: "HAT TRICK", difficulty: "A" },
      { title: "HIGH VOLTAGE", difficulty: "A" },
      { title: "Hydrogen Blueback", difficulty: "A" },
      { title: "IDOL syndrome.", difficulty: "A" },
      { title: "Iris", difficulty: "A" },
      { title: "KOTONOHA ft. Kotoha", difficulty: "A" },
      { title: "LOVE♡SHINE", difficulty: "A" },
      { title: "Lycoris", difficulty: "A" },
      { title: "NΦ CRIME", difficulty: "L" },
      { title: "O/D*20", difficulty: "A" },
      { title: "P.O.W.E.R.", difficulty: "A" },
      { title: "ＰＡＳＴＥＬＩＳＭ", difficulty: "A" },
      { title: "PERFECT HUMAN", difficulty: "A" },
      { title: "Phoenix", difficulty: "A" },
      { title: "POODLE", difficulty: "A" },
      { title: "Shapeshifter", difficulty: "A" },
      { title: "smooooch・∀・", difficulty: "A" },
      { title: "smooooch・∀・ (Snail's House Remix)", difficulty: "A" },
      { title: "snow storm", difficulty: "A" },
      { title: "Summerblue", difficulty: "A" },
      { title: "TITANIUM RIDERS", difficulty: "A" },
      { title: "toy boxer", difficulty: "A" },
      { title: "Turii ～Panta rhei～", difficulty: "A" },
      { title: "Umbral", difficulty: "A" },
      { title: "yellow head joe", difficulty: "A" },
      { title: "Zenius -I- vanisher", difficulty: "A" },
      { title: "ZEROIN ON THE LIGHT", difficulty: "A" },
      { title: "アタシ完全絶対正義ちゃん！", difficulty: "A" },
      { title: "アルストロメリア", difficulty: "A" },
      { title: "オッド♡ラヴィ", difficulty: "A" },
      { title: "オブソミート", difficulty: "A" },
      { title: "オルタネイトβ", difficulty: "A" },
      { title: "キスキツネ", difficulty: "A" },
      { title: "ギャ・ギャ・ギャ・ギャラクシー！", difficulty: "A" },
      { title: "シル・ヴ・プレジデント", difficulty: "A" },
      { title: "シンデレラ", difficulty: "A" },
      { title: "ドリムチウ", difficulty: "A" },
      { title: "ナイトフィクション", difficulty: "A" },
      { title: "ハイ*ビスカス ft. Kanae Asaba", difficulty: "A" },
      { title: "ビビデバ", difficulty: "A" },
      { title: "ベィスドロップ・フリークス", difficulty: "A" },
      { title: "愛包ダンスホール", difficulty: "A" },
      { title: "夏風邪デスコ", difficulty: "A" },
      { title: "華爛漫 -Flowers-", difficulty: "A" },
      { title: "口カラ凸ゲキ", difficulty: "A" },
      { title: "純真可憐デザイア", difficulty: "A" },
      { title: "神っぽいな", difficulty: "A" },
      { title: "弾幕信仰", difficulty: "A" },
      { title: "中華急行", difficulty: "A" },
      { title: "冬椿 ft. Kanae Asaba", difficulty: "A" },
      { title: "閉塞的フレーション", difficulty: "A" },
      { title: "妖隠し -あやかしかくし-", difficulty: "A" },
      { title: "朧", difficulty: "A" },
      { title: "好吃来世deエレクトリック", difficulty: "A" },
    ],
    "11": [
      { title: "3V0", difficulty: "A" },
      { title: "405nm (Ryu☆mix)", difficulty: "A" },
      { title: "Amazing Mirage", difficulty: "A" },
      { title: "AMRITA -不滅ノ花-", difficulty: "A" },
      { title: "ANTHEM LANDING", difficulty: "A" },
      { title: "B4U(BEMANI FOR YOU MIX)", difficulty: "A" },
      { title: "Banger Banger Banger Banger", difficulty: "A" },
      { title: "bloomin' feeling", difficulty: "A" },
      { title: "Bow shock!!", difficulty: "A" },
      { title: "Burning Flame", difficulty: "A" },
      { title: "CHAOTIC SUNBIRD", difficulty: "A" },
      { title: "Chemical Colours", difficulty: "A" },
      { title: "CHRONO DIVER -NORNIR-", difficulty: "A" },
      { title: "Constellation", difficulty: "A" },
      { title: "CONTRACT", difficulty: "A" },
      { title: "Crazy Jackpot", difficulty: "A" },
      { title: "crew", difficulty: "A" },
      { title: "Echoes of Sunfall", difficulty: "A" },
      { title: "Elektrick U-Phoria", difficulty: "A" },
      { title: "ELYSIUM", difficulty: "A" },
      { title: "Ember Lights", difficulty: "A" },
      { title: "everlastingeuphoria:", difficulty: "A" },
      { title: "GloriosA", difficulty: "A" },
      { title: "GOLD RUSH", difficulty: "A" },
      { title: "I'm so Happy", difficulty: "A" },
      { title: "KAMAITACHI", difficulty: "A" },
      { title: "Kung-fu Empire", difficulty: "A" },
      { title: "Like+it!", difficulty: "A" },
      { title: "Line 4 Ruin", difficulty: "A" },
      { title: "Macuilxochitl", difficulty: "A" },
      { title: "Mukade", difficulty: "A" },
      { title: "New Decade IIDX Edition", difficulty: "A" },
      { title: "Nothing but Theory", difficulty: "A" },
      { title: "Override", difficulty: "A" },
      { title: "Plea Per Phase", difficulty: "A" },
      { title: "POLꞰAMAИIA", difficulty: "A" },
      { title: "POODLE", difficulty: "L" },
      { title: "RAVE SYNDROME", difficulty: "A" },
      { title: "RED ZONE", difficulty: "A" },
      { title: "REVOLVER", difficulty: "A" },
      { title: "Ruler or Loser", difficulty: "A" },
      { title: "Secrets", difficulty: "A" },
      { title: "Show Me All Your Love", difficulty: "A" },
      { title: "Submerge Serenade", difficulty: "A" },
      { title: "TECHNO RUMBLE", difficulty: "A" },
      { title: "THE CANNONBALLER", difficulty: "A" },
      { title: "Time Distortion pt.2(IIDX Edit)", difficulty: "A" },
      { title: "Übertreffen", difficulty: "A" },
      { title: "UMMU", difficulty: "A" },
      { title: "winkle 2 winkle", difficulty: "A" },
      { title: "Xepher", difficulty: "A" },
      { title: "Ypsilon", difficulty: "A" },
      { title: "ZENDEGI DANCE", difficulty: "A" },
      { title: "ZEPHYRANTHES", difficulty: "A" },
      { title: "ZEИITH", difficulty: "A" },
      { title: "えだまめカレークッキング", difficulty: "A" },
      { title: "きみのせかい", difficulty: "A" },
      { title: "シル・ヴ・プレジデント", difficulty: "L" },
      { title: "ちょえちょえまぎか", difficulty: "A" },
      { title: "パ→ピ→プ→Yeah!", difficulty: "A" },
      { title: "ハードベース・フェスタ", difficulty: "A" },
      { title: "ハイテックトキオ", difficulty: "A" },
      { title: "フォニイ", difficulty: "A" },
      { title: "マーシャル・マキシマイザー", difficulty: "A" },
      { title: "ミッドナイト☆WAR", difficulty: "A" },
      { title: "メズマライザー", difficulty: "A" },
      { title: "ランカーキラーガール", difficulty: "A" },
      { title: "仮想空間の旅人たち", difficulty: "A" },
      { title: "華蝶風雪", difficulty: "A" },
      { title: "覚悟せよ！エンタンメ～ン ～より身の切り売り自暴自棄版～", difficulty: "A" },
      { title: "狂水一華", difficulty: "A" },
      { title: "君のハートにロックオン", difficulty: "A" },
      { title: "月とミルク", difficulty: "A" },
      { title: "打打打打打打打打打打", difficulty: "A" },
      { title: "冬椿 ft. Kanae Asaba", difficulty: "L" },
      { title: "爆ぜりゃんせ", difficulty: "A" },
      { title: "夢縁", difficulty: "A" },
      { title: "無意識のフィロソフィア", difficulty: "A" },
      { title: "勇者", difficulty: "A" },
      { title: "龍と少女とデコヒーレンス", difficulty: "A" },
      { title: "龍王の霊廟(Mausoleum Of The Primal Dragon)", difficulty: "A" },
      { title: "量子の海のリントヴルム", difficulty: "A" },
      { title: "麗 ～うらら～", difficulty: "A" },
      { title: "惑星☆ロリポップ", difficulty: "A" },
      { title: "儚き恋の華", difficulty: "A" },
      { title: "Selfish Sweet", difficulty: "L" },
    ],
    "12": [
      { title: "[ ]DENTITY", difficulty: "A" },
      { title: "†渚の小悪魔ラヴリィ～レイディオ†(IIDX EDIT)", difficulty: "A" },
      { title: "AA", difficulty: "A" },
      { title: "Aqvion", difficulty: "A" },
      { title: "BLACK or WHITE?", difficulty: "A" },
      { title: "Bring The Fire", difficulty: "A" },
      { title: "Burning Flame", difficulty: "L" },
      { title: "Caldwell 99", difficulty: "L" },
      { title: "Carry Me Away", difficulty: "A" },
      { title: "ChaserXX", difficulty: "L" },
      { title: "Chrono Diver -PENDULUMs-", difficulty: "A" },
      { title: "Close the World feat.a☆ru", difficulty: "L" },
      { title: "Cross Fire", difficulty: "A" },
      { title: "CUE CUE RESCUE", difficulty: "L" },
      { title: "DEATH†ZIGOQ ～怒りの高速爆走野郎～", difficulty: "L" },
      { title: "destination", difficulty: "A" },
      { title: "dica dica", difficulty: "A" },
      { title: "Dr. Chemical & Killing Machine", difficulty: "A" },
      { title: "entelecheia", difficulty: "A" },
      { title: "Evans", difficulty: "A" },
      { title: "F", difficulty: "A" },
      { title: "Feel The Beat", difficulty: "A" },
      { title: "Fegrix", difficulty: "A" },
      { title: "Flämingo", difficulty: "A" },
      { title: "FlyAway", difficulty: "A" },
      { title: "frequent", difficulty: "A" },
      { title: "GENE", difficulty: "A" },
      { title: "glacia", difficulty: "A" },
      { title: "God Mind", difficulty: "A" },
      { title: "GuNGNiR", difficulty: "L" },
      { title: "hora de verdad", difficulty: "A" },
      { title: "HYENA", difficulty: "L" },
      { title: "Lethal Weapon", difficulty: "A" },
      { title: "LIGHTNING STRIKES", difficulty: "L" },
      { title: "MARLIN", difficulty: "A" },
      { title: "Mid-Corner (Magic Maker)", difficulty: "A" },
      { title: "No Border", difficulty: "A" },
      { title: "Nothing but Theory", difficulty: "L" },
      { title: "perditus†paradisus", difficulty: "A" },
      { title: "Phoenix", difficulty: "L" },
      { title: "Pinky Happy Crazy", difficulty: "A" },
      { title: "Primitive Vibes", difficulty: "A" },
      { title: "RED ZONE", difficulty: "L" },
      { title: "Roar of Chronos", difficulty: "A" },
      { title: "sakura storm", difficulty: "A" },
      { title: "Satellite Burst", difficulty: "A" },
      { title: "Scripted Connection⇒ A mix", difficulty: "A" },
      { title: "Sigmund", difficulty: "L" },
      { title: "snow storm", difficulty: "L" },
      { title: "SOLAR ECLIPSE", difficulty: "A" },
      { title: "STARLIGHT DANCEHALL", difficulty: "L" },
      { title: "Symmetry", difficulty: "A" },
      { title: "SμG@R RU$#", difficulty: "A" },
      { title: "The Limbo", difficulty: "A" },
      { title: "The Sampling Paradise", difficulty: "A" },
      { title: "TIEFSEE", difficulty: "A" },
      { title: "Todestrieb", difficulty: "A" },
      { title: "True Blue", difficulty: "A" },
      { title: "u gotta beat", difficulty: "A" },
      { title: "Uaigh Gealaí", difficulty: "A" },
      { title: "VANESSA", difficulty: "L" },
      { title: "Verflucht", difficulty: "L" },
      { title: "Visterhv", difficulty: "A" },
      { title: "Without Heaven", difficulty: "A" },
      { title: "ZZ", difficulty: "A" },
      { title: "ΕΛΠΙΣ", difficulty: "L" },
      { title: "アラビアン ハイパー ナイト", difficulty: "A" },
      { title: "カジノファイヤーことみちゃん", difficulty: "L" },
      { title: "スキッテイエェエエェ!!!!", difficulty: "A" },
      { title: "ハイテックトキオ", difficulty: "L" },
      { title: "華爛漫 -Flowers-", difficulty: "L" },
      { title: "君のハートにロックオン", difficulty: "L" },
      { title: "紅牡丹", difficulty: "A" },
      { title: "黒髪乱れし修羅となりて", difficulty: "A" },
      { title: "紫陽花 -AZISAI-", difficulty: "L" },
      { title: "神っぽいな", difficulty: "L" },
      { title: "刃図羅", difficulty: "A" },
      { title: "聖人の塔", difficulty: "L" },
      { title: "超青少年ノ為ノ超多幸ナ超古典的超舞曲", difficulty: "L" },
      { title: "天空の夜明け", difficulty: "A" },
      { title: "天邪鬼", difficulty: "A" },
      { title: "伐折羅-vajra-", difficulty: "A" },
      { title: "龍と少女とデコヒーレンス", difficulty: "L" },
      { title: "恋する☆宇宙戦争っ！！", difficulty: "L" },
      { title: "儚キ戀ノ幻想譚", difficulty: "A" },
      { title: "⁽⁽ଘ( ˙꒳˙ )ଓ⁾⁾ beyond reason", difficulty: "A" },
      { title: "2 Be Continued", difficulty: "A" },
      { title: "Begin", difficulty: "A" },
      { title: "Disco Killer Music Lover", difficulty: "A" },
      { title: "From Human Blood", difficulty: "A" },
      { title: "Memoria Obscura", difficulty: "A" },
      { title: "POLꞰAMAИIA", difficulty: "L" },
      { title: "RALLY '25", difficulty: "A" },
      { title: "Space Battleship S4TØ", difficulty: "A" },
      { title: "Submerge Serenade", difficulty: "L" },
      { title: "ビビッド ☆+*。キラキライム", difficulty: "A" },
    ],
  },
  "PEAK": {
    "8-10": [
      { title: "BAD BOY BASS!! (dj Remo-con MIX)", difficulty: "A" },
      { title: "CALL", difficulty: "A" },
      { title: "EMPTY OF THE SKY", difficulty: "A" },
      { title: "four-leaf", difficulty: "A" },
      { title: "RIDE ON THE LIGHT (HI GREAT MIX)", difficulty: "A" },
      { title: "AGEHA", difficulty: "A" },
      { title: "ALL I NEED YOUR LOVE", difficulty: "A" },
      { title: "CaptivAte～裁き～", difficulty: "A" },
      { title: "Clione", difficulty: "A" },
      { title: "Don't Stop The Music feat. Kanae Asaba", difficulty: "A" },
      { title: "METALLIC MIND", difficulty: "A" },
      { title: "Monkey Dance", difficulty: "A" },
      { title: "neogenesis", difficulty: "A" },
      { title: "Psycho Sheep Riddim", difficulty: "A" },
      { title: "RUGGED ASH", difficulty: "A" },
      { title: "SPEEDY CAT", difficulty: "A" },
      { title: "Too Late Snow", difficulty: "A" },
      { title: "ＵＬＴｉＭΛＴＥ", difficulty: "A" },
      { title: "Under the Sky", difficulty: "A" },
      { title: "まほろば", difficulty: "A" },
      { title: "リメンバーリメンバー", difficulty: "A" },
      { title: "太陽～T・A・I・Y・O～", difficulty: "A" },
      { title: "大桟橋", difficulty: "A" },
      { title: "ADVANCE", difficulty: "A" },
      { title: "ALFARSHEAR 双神威に廻る夢", difficulty: "A" },
      { title: "alla turca con passione", difficulty: "A" },
      { title: "Apocalypse ～dirge of swans～", difficulty: "A" },
      { title: "B4U", difficulty: "A" },
      { title: "BABY LOVE", difficulty: "A" },
      { title: "Bahram Attack-猫叉Master Remix-", difficulty: "A" },
      { title: "Best of Me", difficulty: "A" },
      { title: "CaptivAte～誓い～", difficulty: "A" },
      { title: "Chain of pain", difficulty: "A" },
      { title: "Chasing After YOU ～夢の欠片～ ft. 小林マナ", difficulty: "A" },
      { title: "Cyber Force -DJ Yoshitaka Remix-", difficulty: "A" },
      { title: "D.A.N.C.E.!", difficulty: "A" },
      { title: "DENIM", difficulty: "A" },
      { title: "DIVE ～INTO YOUR HEART～", difficulty: "A" },
      { title: "Do What You Want", difficulty: "A" },
      { title: "Don't be afraid myself", difficulty: "A" },
      { title: "DXY!", difficulty: "A" },
      { title: "e-motion 2003 -romantic extra-", difficulty: "A" },
      { title: "EURO-ROMANCE", difficulty: "A" },
      { title: "FEEL IT", difficulty: "A" },
      { title: "Fly Above (Vicissitude Remix)", difficulty: "A" },
      { title: "Freeway Shuffle", difficulty: "A" },
      { title: "Geirskögul", difficulty: "A" },
      { title: "HYPER EUROBEAT (2DX style)", difficulty: "A" },
      { title: "Infinite cave", difficulty: "A" },
      { title: "Jack", difficulty: "A" },
      { title: "Jumper", difficulty: "A" },
      { title: "Keep it-秋葉工房mix-", difficulty: "A" },
      { title: "LETHEBOLG ～双神威に斬り咲けり～", difficulty: "A" },
      { title: "Miracle 5ympho X", difficulty: "A" },
      { title: "Musik LoverZ", difficulty: "A" },
      { title: "Narcissus At Oasis", difficulty: "A" },
      { title: "NEW GENERATION -もう、お前しか見えない-", difficulty: "A" },
      { title: "PHOTONGENIC", difficulty: "A" },
      { title: "POINT ZERO", difficulty: "A" },
      { title: "Rainbow after snow", difficulty: "A" },
      { title: "Reflection Into the EDEN", difficulty: "A" },
      { title: "Sephirot", difficulty: "A" },
      { title: "She is my wife", difficulty: "A" },
      { title: "Shirdal", difficulty: "A" },
      { title: "Silly Love", difficulty: "A" },
      { title: "So Fabulous !!", difficulty: "A" },
      { title: "Sphere", difficulty: "A" },
      { title: "Star Trail", difficulty: "A" },
      { title: "Static State", difficulty: "A" },
      { title: "sync", difficulty: "A" },
      { title: "THANK YOU FOR PLAYING", difficulty: "A" },
      { title: "That Feeling", difficulty: "A" },
      { title: "The Hope of Tomorrow", difficulty: "A" },
      { title: "Tori-no-kimochi", difficulty: "A" },
      { title: "Twelfth Style", difficulty: "A" },
      { title: "VIBRΛ", difficulty: "A" },
      { title: "Wonderful Escape", difficulty: "A" },
      { title: "Wuv U", difficulty: "A" },
      { title: "ギョギョっと人魚 爆婚ブライダル", difficulty: "A" },
      { title: "グラナダの風", difficulty: "A" },
      { title: "クルクル☆ラブ～Opioid Peptide MIX～", difficulty: "A" },
      { title: "罪と罰", difficulty: "A" },
      { title: "十六夜セツナ", difficulty: "A" },
      { title: "水上の提督(Short mix from \"幻想水滸伝V\")", difficulty: "A" },
      { title: "恋はどう？モロ◎波動OK☆方程式!!", difficulty: "A" },
      { title: "evergreen", difficulty: "A" },
    ],
    "11": [
      { title: "24th Century BOY", difficulty: "A" },
      { title: "Abraxas", difficulty: "A" },
      { title: "AFRO KNUCKLE", difficulty: "A" },
      { title: "Amethyst", difficulty: "A" },
      { title: "Angelic Jelly", difficulty: "A" },
      { title: "Around the Future", difficulty: "A" },
      { title: "Aurora", difficulty: "A" },
      { title: "Back Spin Sweeper", difficulty: "A" },
      { title: "Battleground", difficulty: "A" },
      { title: "Be quiet", difficulty: "A" },
      { title: "Blame", difficulty: "A" },
      { title: "Blind Justice ～Torn souls, Hurt Faiths ～", difficulty: "A" },
      { title: "BLOCKS", difficulty: "A" },
      { title: "Blue Rain", difficulty: "A" },
      { title: "BRAVE OUT", difficulty: "L" },
      { title: "Broadbanded", difficulty: "A" },
      { title: "CaptivAte2～覚醒～", difficulty: "A" },
      { title: "chaos eater -IIDX edition-", difficulty: "A" },
      { title: "Cosmic Cat", difficulty: "A" },
      { title: "Critical Crystal", difficulty: "A" },
      { title: "Cyber True Color", difficulty: "A" },
      { title: "D.C.fish", difficulty: "A" },
      { title: "DESIRE", difficulty: "A" },
      { title: "diagram", difficulty: "A" },
      { title: "Do it!! Do it!!", difficulty: "A" },
      { title: "DROP", difficulty: "A" },
      { title: "Eine Haube ～聖地の果てにあるもの～", difficulty: "A" },
      { title: "Farewell to Marrakech", difficulty: "A" },
      { title: "Flash Back 90's", difficulty: "L" },
      { title: "FLOWER", difficulty: "A" },
      { title: "Funny shuffle", difficulty: "A" },
      { title: "Ganymede", difficulty: "A" },
      { title: "Get Higher", difficulty: "A" },
      { title: "GHOST", difficulty: "A" },
      { title: "Giudecca", difficulty: "A" },
      { title: "GOBBLE", difficulty: "A" },
      { title: "Harmony and Lovely", difficulty: "A" },
      { title: "Holic", difficulty: "A" },
      { title: "Insane Techniques", difficulty: "A" },
      { title: "Into The Madness", difficulty: "A" },
      { title: "kors k's How to make OTOGE CORE", difficulty: "A" },
      { title: "m1dy Deluxe", difficulty: "A" },
      { title: "MENTAL MELTDOWN", difficulty: "A" },
      { title: "Nasty Techniques", difficulty: "A" },
      { title: "neogenesis", difficulty: "L" },
      { title: "Next Tales 2 Oath (IIDX 20th Anniv \"Ring\" Theme)", difficulty: "A" },
      { title: "Night sky", difficulty: "A" },
      { title: "OTOKOZAKA", difficulty: "A" },
      { title: "Pout", difficulty: "A" },
      { title: "Programmed World", difficulty: "A" },
      { title: "quasar", difficulty: "A" },
      { title: "Queen Kaguya", difficulty: "A" },
      { title: "R5", difficulty: "A" },
      { title: "rainbow flyer", difficulty: "A" },
      { title: "rainbow guitar weeps", difficulty: "A" },
      { title: "RESONATE 1794", difficulty: "A" },
      { title: "Rising in the Sun(original mix)", difficulty: "A" },
      { title: "RISLIM -Remix-", difficulty: "A" },
      { title: "S!ck", difficulty: "A" },
      { title: "Sakura Mirage", difficulty: "A" },
      { title: "SCHWARZSCHILD FIELD", difficulty: "A" },
      { title: "Scripted Connection⇒ N mix", difficulty: "L" },
      { title: "Second Heaven", difficulty: "A" },
      { title: "Seraph", difficulty: "A" },
      { title: "Spica", difficulty: "A" },
      { title: "squall", difficulty: "A" },
      { title: "STEEL NEEDLE", difficulty: "A" },
      { title: "SUPER HEROINE!!", difficulty: "A" },
      { title: "The Dirty of Loudness", difficulty: "A" },
      { title: "THE LAST STRIKER", difficulty: "A" },
      { title: "tripping contact(teranoid&MC Natsack Remix)", difficulty: "A" },
      { title: "Unicorn tail", difficulty: "A" },
      { title: "waxing and wanding", difficulty: "A" },
      { title: "Yum Yum Jelly", difficulty: "A" },
      { title: "ZED", difficulty: "A" },
      { title: "オールトの雲", difficulty: "A" },
      { title: "セロトニン", difficulty: "A" },
      { title: "合体せよ！ストロングイェーガー！！ (Ryu☆ remix)", difficulty: "A" },
      { title: "蛇神", difficulty: "A" },
      { title: "青の洞窟", difficulty: "A" },
      { title: "断罪の一花", difficulty: "A" },
      { title: "超青少年ノ為ノ超多幸ナ超古典的超舞曲", difficulty: "A" },
      { title: "牧神笛吹きて", difficulty: "A" },
      { title: "命の標本", difficulty: "A" },
      { title: "旅人リラン", difficulty: "A" },
      { title: "LAB", difficulty: "L" },
    ],
    "12": [
      { title: "1116", difficulty: "A" },
      { title: "∀", difficulty: "A" },
      { title: "3y3s", difficulty: "A" },
      { title: "ANCHOR", difficulty: "A" },
      { title: "Bad Encryption", difficulty: "A" },
      { title: "Bad Maniacs", difficulty: "A" },
      { title: "Beyond Evolution", difficulty: "A" },
      { title: "Binary Black Hole", difficulty: "A" },
      { title: "Blue Rain", difficulty: "L" },
      { title: "Broken", difficulty: "A" },
      { title: "Chaotoxin", difficulty: "A" },
      { title: "CODE:0", difficulty: "L" },
      { title: "Colorful Cookie", difficulty: "A" },
      { title: "Colors (radio edit)", difficulty: "A" },
      { title: "Confiserie", difficulty: "A" },
      { title: "CONTRACT", difficulty: "L" },
      { title: "Dahlia", difficulty: "A" },
      { title: "Dances with Snow Fairies", difficulty: "L" },
      { title: "Devil's Gear", difficulty: "A" },
      { title: "DIAVOLO", difficulty: "A" },
      { title: "DOMINION", difficulty: "A" },
      { title: "DORNWALD ～Junge～", difficulty: "A" },
      { title: "Drop Syndicate", difficulty: "A" },
      { title: "EMERALDAS", difficulty: "A" },
      { title: "EROICA", difficulty: "A" },
      { title: "Feel The Beat", difficulty: "L" },
      { title: "FIRE FIRE", difficulty: "A" },
      { title: "four pieces of heaven", difficulty: "L" },
      { title: "Ganymede", difficulty: "L" },
      { title: "Ghost Pulse", difficulty: "A" },
      { title: "gigadelic", difficulty: "A" },
      { title: "Go Ahead!!", difficulty: "A" },
      { title: "Go Beyond!!", difficulty: "A" },
      { title: "HADES", difficulty: "A" },
      { title: "hard-wired", difficulty: "A" },
      { title: "Illegal Function Call", difficulty: "L" },
      { title: "Innocent Walls", difficulty: "A" },
      { title: "KAMAITACHI", difficulty: "L" },
      { title: "Last Dance", difficulty: "A" },
      { title: "Mare Nectaris", difficulty: "A" },
      { title: "MEGAERA", difficulty: "A" },
      { title: "Megalara Garuda", difficulty: "A" },
      { title: "Meissa", difficulty: "A" },
      { title: "MENDES", difficulty: "A" },
      { title: "neu", difficulty: "A" },
      { title: "Nightmare before oversleep", difficulty: "A" },
      { title: "ONE AND ONLY", difficulty: "A" },
      { title: "One More Lovely", difficulty: "A" },
      { title: "Proof of the existence", difficulty: "A" },
      { title: "Ristaccia", difficulty: "A" },
      { title: "Scripted Connection⇒ A mix", difficulty: "L" },
      { title: "Scripted Connection⇒ H mix", difficulty: "L" },
      { title: "Sense 2007", difficulty: "A" },
      { title: "SOLID STATE SQUAD", difficulty: "A" },
      { title: "STEEL NEEDLE", difficulty: "L" },
      { title: "TECHNOPHOBIA", difficulty: "A" },
      { title: "THE F∀UST", difficulty: "A" },
      { title: "The Limbo", difficulty: "L" },
      { title: "THE PEERLESS UNDER HEAVEN", difficulty: "A" },
      { title: "Thor's Hammer", difficulty: "A" },
      { title: "Twelfth Style", difficulty: "L" },
      { title: "uən", difficulty: "A" },
      { title: "V", difficulty: "A" },
      { title: "X-DEN", difficulty: "A" },
      { title: "Xerulean", difficulty: "A" },
      { title: "Zirkfied", difficulty: "A" },
      { title: "お菓子の王国", difficulty: "A" },
      { title: "カゴノトリ～弐式～", difficulty: "A" },
      { title: "シムルグの目醒め", difficulty: "A" },
      { title: "たまゆら", difficulty: "A" },
      { title: "ピアノ協奏曲第1番”蠍火” (BlackY Remix)", difficulty: "A" },
      { title: "狂イ咲ケ焔ノ華", difficulty: "A" },
      { title: "金野火織の金色提言", difficulty: "A" },
      { title: "紫陽花 -AZISAI-", difficulty: "A" },
      { title: "疾風迅雷", difficulty: "L" },
      { title: "少年は空を辿る", difficulty: "A" },
      { title: "雪月花", difficulty: "A" },
      { title: "嘆きの樹", difficulty: "A" },
      { title: "津軽雪", difficulty: "A" },
      { title: "天使のカンタータ -Cantata of Angels-", difficulty: "A" },
      { title: "東京神話", difficulty: "A" },
      { title: "卑弥呼", difficulty: "A" },
      { title: "不沈艦CANDY", difficulty: "A" },
      { title: "煉獄のエルフェリア", difficulty: "A" },
      { title: "閠槞彁の願い", difficulty: "A" },
      { title: "ιgniЯRuina", difficulty: "A" },
    ],
  },
  "CHORD": {
    "8-10": [
      { title: "Fly Above", difficulty: "A" },
      { title: "A MINSTREL ～ ver. short-scape ～", difficulty: "A" },
      { title: "chrono diver -fragment-", difficulty: "A" },
      { title: "Crank It", difficulty: "A" },
      { title: "Element of SPADA", difficulty: "A" },
      { title: "High School Love", difficulty: "A" },
      { title: "Hurry Hurry", difficulty: "A" },
      { title: "LUV CAN SAVE U", difficulty: "A" },
      { title: "Mind Mapping", difficulty: "A" },
      { title: "SURVIVOR", difficulty: "A" },
      { title: "thunder HOUSE NATION Remix", difficulty: "A" },
      { title: "イガク", difficulty: "A" },
      { title: "たからもの", difficulty: "A" },
      { title: "れとりば！", difficulty: "A" },
      { title: "雨のちパノラマセカイ", difficulty: "A" },
      { title: "可愛くてごめん", difficulty: "A" },
      { title: "黒紅掬い", difficulty: "A" },
      { title: "1001 -ESCAPE-", difficulty: "A" },
      { title: "8bit Princess", difficulty: "A" },
      { title: "Aeterna", difficulty: "A" },
      { title: "Akatsuki", difficulty: "A" },
      { title: "Beat Radiance", difficulty: "A" },
      { title: "being torn the sky", difficulty: "A" },
      { title: "Bloody Tears(IIDX EDITION)", difficulty: "A" },
      { title: "Breaking the ground", difficulty: "A" },
      { title: "chrono diver -fragment-", difficulty: "L" },
      { title: "CROSSROAD ～Left Story～", difficulty: "A" },
      { title: "Damage Per Second", difficulty: "L" },
      { title: "Dazzlin' Darlin", difficulty: "A" },
      { title: "Dreaming Dream", difficulty: "A" },
      { title: "Drive Me Crazy", difficulty: "A" },
      { title: "EDEN", difficulty: "A" },
      { title: "Eleanor", difficulty: "A" },
      { title: "EMOTiON TRiPPER", difficulty: "A" },
      { title: "Fantasia", difficulty: "A" },
      { title: "FERMI♡PARADOX", difficulty: "A" },
      { title: "Follow Tomorrow", difficulty: "A" },
      { title: "get set mind", difficulty: "A" },
      { title: "GRID KNIGHT", difficulty: "A" },
      { title: "LADS", difficulty: "A" },
      { title: "LUV CAN SAVE U", difficulty: "L" },
      { title: "Mermaid girl", difficulty: "A" },
      { title: "Mighty Cutie", difficulty: "A" },
      { title: "Mind Mapping", difficulty: "L" },
      { title: "OOO", difficulty: "A" },
      { title: "passionate fate", difficulty: "A" },
      { title: "Secret Rouge", difficulty: "A" },
      { title: "SHION", difficulty: "A" },
      { title: "SigSig", difficulty: "A" },
      { title: "Slumber☆Party", difficulty: "A" },
      { title: "Sorrows", difficulty: "A" },
      { title: "Sugarplum", difficulty: "A" },
      { title: "Sweet Radar", difficulty: "A" },
      { title: "The Commanders", difficulty: "A" },
      { title: "Wing of Hearts", difficulty: "A" },
      { title: "XANADU OF TWO", difficulty: "A" },
      { title: "アイドル", difficulty: "A" },
      { title: "エクスプロウル", difficulty: "A" },
      { title: "オドループ", difficulty: "A" },
      { title: "きゅんです。", difficulty: "A" },
      { title: "ゲシュタルト", difficulty: "A" },
      { title: "ここからよろしく大作戦143", difficulty: "A" },
      { title: "セピアの軌跡 ft. 天宮みや(少女フラクタル)", difficulty: "A" },
      { title: "デビルじゃないもん", difficulty: "A" },
      { title: "ハルイロメロディー", difficulty: "A" },
      { title: "ポラリスノウタ", difficulty: "A" },
      { title: "ミラージュ・レジデンス", difficulty: "A" },
      { title: "めでてえ", difficulty: "A" },
      { title: "ラブキラ☆スプラッシュ", difficulty: "A" },
      { title: "可愛くてごめん", difficulty: "L" },
      { title: "夏の匂い。キミの残像。 ft. Kanae Asaba", difficulty: "A" },
      { title: "怪物", difficulty: "A" },
      { title: "月と夢の跡 ft. マナ", difficulty: "A" },
      { title: "月光", difficulty: "A" },
      { title: "昏き甲鉄のヴェルガ", difficulty: "A" },
      { title: "取り残された美術(Arranged:HiZuMi)", difficulty: "A" },
      { title: "朱と碧のランページ", difficulty: "A" },
      { title: "消極的セツナイズム", difficulty: "A" },
      { title: "湘南ロンリーMIDNIGHT RAIN", difficulty: "A" },
      { title: "進捗ダメダメです", difficulty: "A" },
      { title: "酔いどれ知らず", difficulty: "A" },
      { title: "突撃!ガラスのニーソ姫!", difficulty: "A" },
      { title: "梅雪夜", difficulty: "A" },
      { title: "翼", difficulty: "L" },
      { title: "凛として咲く花の如く", difficulty: "A" },
      { title: "OVER TIME", difficulty: "L" },
    ],
    "11": [
      { title: "≡+≡", difficulty: "A" },
      { title: "AGEHA", difficulty: "L" },
      { title: "ALBA -黎明-", difficulty: "A" },
      { title: "Anisakis -somatic mutation type\"Forza\"-", difficulty: "A" },
      { title: "apo:llioth", difficulty: "A" },
      { title: "Bahram Attack-猫叉Master Remix-", difficulty: "L" },
      { title: "Bang-Boo Bumble", difficulty: "A" },
      { title: "Beyond The Earth", difficulty: "A" },
      { title: "Beyond The Seven", difficulty: "A" },
      { title: "BLUST OF WIND", difficulty: "L" },
      { title: "BroGamer", difficulty: "A" },
      { title: "CaptivAte～浄化～", difficulty: "A" },
      { title: "C-C-C-N-N-N", difficulty: "A" },
      { title: "Chronos", difficulty: "L" },
      { title: "City Never Sleeps (IIDX Edition)", difficulty: "A" },
      { title: "Cookie Bouquets", difficulty: "A" },
      { title: "DAZZLE ATTACK", difficulty: "A" },
      { title: "Divine Heaven", difficulty: "A" },
      { title: "EDEN", difficulty: "L" },
      { title: "Egret and Willow", difficulty: "A" },
      { title: "Element of SPADA", difficulty: "L" },
      { title: "Emera", difficulty: "A" },
      { title: "examination leave", difficulty: "A" },
      { title: "Fervidex", difficulty: "A" },
      { title: "FREEDOM", difficulty: "A" },
      { title: "HEISEI", difficulty: "A" },
      { title: "HELL SCAPER -Last Escape Remix-", difficulty: "A" },
      { title: "HIGH", difficulty: "L" },
      { title: "IDOL syndrome.", difficulty: "L" },
      { title: "in the Sky", difficulty: "A" },
      { title: "Journey", difficulty: "L" },
      { title: "KING", difficulty: "A" },
      { title: "lowercase lifetime", difficulty: "A" },
      { title: "Lucy", difficulty: "A" },
      { title: "MVP", difficulty: "A" },
      { title: "No Tears", difficulty: "A" },
      { title: "Outbreak", difficulty: "A" },
      { title: "Pollinosis", difficulty: "A" },
      { title: "PopなEDEN", difficulty: "A" },
      { title: "Punch Love♡仮面", difficulty: "L" },
      { title: "R∞tAge", difficulty: "A" },
      { title: "Raspberry Potion (feat.あれたん♡ & ぎゃるのしん☆)", difficulty: "A" },
      { title: "Realize Maze", difficulty: "A" },
      { title: "Romanticが止まらない", difficulty: "A" },
      { title: "SHADE", difficulty: "A" },
      { title: "Shadow World", difficulty: "A" },
      { title: "smooooch・∀・", difficulty: "L" },
      { title: "Speculation", difficulty: "A" },
      { title: "Stargazing Trip ～星 探す旅～ ft. 小林マナ", difficulty: "A" },
      { title: "STARLIGHT DANCEHALL", difficulty: "A" },
      { title: "STARLIGHT JUNCTION", difficulty: "L" },
      { title: "THE DEEP STRIKER", difficulty: "A" },
      { title: "the trigger of innocence", difficulty: "L" },
      { title: "Time to Air", difficulty: "A" },
      { title: "Tropical April", difficulty: "A" },
      { title: "V2", difficulty: "A" },
      { title: "VALKYRIAS -英雄誕生-", difficulty: "A" },
      { title: "Ventriloquist", difficulty: "A" },
      { title: "Volcanic Dragon", difficulty: "A" },
      { title: "Wanna Party?", difficulty: "L" },
      { title: "Welcome", difficulty: "A" },
      { title: "WISE UP!", difficulty: "L" },
      { title: "Xyndrome", difficulty: "A" },
      { title: "アイドル", difficulty: "L" },
      { title: "オドループ", difficulty: "L" },
      { title: "グッバイ宣言", difficulty: "A" },
      { title: "ここからよろしく大作戦143", difficulty: "L" },
      { title: "たからもの", difficulty: "L" },
      { title: "ドッキン☆サマーあばんちゅーる", difficulty: "A" },
      { title: "ハオ", difficulty: "A" },
      { title: "バッドエンド・シンドローム", difficulty: "A" },
      { title: "ミュージック・アワー", difficulty: "A" },
      { title: "めうめうぺったんたん！！ (ZAQUVA Remix)", difficulty: "A" },
      { title: "ユミル", difficulty: "A" },
      { title: "ラビットホール", difficulty: "A" },
      { title: "果たせぬ約束 ft. 小林マナ", difficulty: "A" },
      { title: "怪物", difficulty: "L" },
      { title: "少年リップルズ", difficulty: "A" },
      { title: "寝起きヤシの木", difficulty: "A" },
      { title: "無双", difficulty: "A" },
      { title: "恋は白帯、サンシロー", difficulty: "L" },
      { title: "錬成人間トリコロイダー", difficulty: "A" },
      { title: "凛として咲く花の如く", difficulty: "L" },
      { title: "朧", difficulty: "L" },
      { title: "鴉", difficulty: "A" },
      { title: "kors k's Let's make an Image Song!", difficulty: "A" },
      { title: "ゲシュタルト", difficulty: "L" },
    ],
    "12": [
      { title: "#The_Relentless", difficulty: "L" },
      { title: "〆", difficulty: "A" },
      { title: "A MINSTREL ～ ver. short-scape ～", difficulty: "L" },
      { title: "ÆTHER", difficulty: "L" },
      { title: "AKASHIC BREAK", difficulty: "A" },
      { title: "ALBA -黎明-", difficulty: "L" },
      { title: "ALBIDA", difficulty: "A" },
      { title: "ALTERNATOR", difficulty: "A" },
      { title: "Amazing Mirage", difficulty: "L" },
      { title: "Anisakis -somatic mutation type\"Forza\"-", difficulty: "L" },
      { title: "B4U(BEMANI FOR YOU MIX)", difficulty: "L" },
      { title: "Beat Radiance", difficulty: "L" },
      { title: "BIGWAVERS", difficulty: "A" },
      { title: "BITTER CHOCOLATE STRIKER", difficulty: "A" },
      { title: "Boomy and The Boost", difficulty: "A" },
      { title: "Bow shock!!", difficulty: "L" },
      { title: "BroGamer", difficulty: "L" },
      { title: "CHRONO DIVER -NORNIR-", difficulty: "L" },
      { title: "Cosmic Cat", difficulty: "L" },
      { title: "DARK LEGACY", difficulty: "A" },
      { title: "Despair of ELFERIA", difficulty: "A" },
      { title: "Dynamite", difficulty: "A" },
      { title: "Elemental Creation", difficulty: "A" },
      { title: "eRAseRmOToRpHAntOM", difficulty: "A" },
      { title: "EX-MASSIVE FIGHTER", difficulty: "A" },
      { title: "G59", difficulty: "A" },
      { title: "GO OVER WITH GLARE -ROOTAGE 26-", difficulty: "A" },
      { title: "GRID KNIGHT", difficulty: "L" },
      { title: "Here We Go Now", difficulty: "A" },
      { title: "INAZUMA", difficulty: "L" },
      { title: "Initiation", difficulty: "A" },
      { title: "INSOMNIA", difficulty: "A" },
      { title: "JUSTICE/GUILTY feat. Nana Takahashi & 709sec.", difficulty: "A" },
      { title: "KING", difficulty: "L" },
      { title: "Kung-fu Empire", difficulty: "L" },
      { title: "Little Little Princess", difficulty: "L" },
      { title: "LIVE DRIVING!! feat. 花たん", difficulty: "A" },
      { title: "M4K3 1T B0UNC3", difficulty: "A" },
      { title: "Marie Antoinette", difficulty: "L" },
      { title: "mosaic", difficulty: "A" },
      { title: "NEO GENERATOR SEVEN", difficulty: "A" },
      { title: "NNRT", difficulty: "A" },
      { title: "Override", difficulty: "L" },
      { title: "PLASMA SOUL NIGHT feat. Nana Takahashi / 709sec.", difficulty: "A" },
      { title: "Rampage", difficulty: "A" },
      { title: "Rave*it!! Rave*it!!", difficulty: "A" },
      { title: "reunion", difficulty: "A" },
      { title: "RINИE", difficulty: "A" },
      { title: "rommmo", difficulty: "A" },
      { title: "Say YEEEAHH", difficulty: "A" },
      { title: "Secrets", difficulty: "L" },
      { title: "SOLID STATE SQUAD", difficulty: "L" },
      { title: "Sounds Of Summer", difficulty: "A" },
      { title: "Super Rush", difficulty: "A" },
      { title: "THE BRAVE MUST DIE", difficulty: "A" },
      { title: "THE DEEP STRIKER", difficulty: "L" },
      { title: "The Onlyonez", difficulty: "A" },
      { title: "thunder HOUSE NATION Remix", difficulty: "L" },
      { title: "Thunderbolt", difficulty: "A" },
      { title: "Time to Air", difficulty: "L" },
      { title: "Triple Counter", difficulty: "A" },
      { title: "TROOPERS", difficulty: "A" },
      { title: "Venom", difficulty: "A" },
      { title: "VOX UP", difficulty: "A" },
      { title: "waxing and wanding", difficulty: "L" },
      { title: "Welcome", difficulty: "L" },
      { title: "グッバイ宣言", difficulty: "L" },
      { title: "スパークリング☆彡ハイパーチューン！！", difficulty: "A" },
      { title: "フォニイ", difficulty: "L" },
      { title: "仮想空間の旅人たち", difficulty: "L" },
      { title: "華蝶風雪", difficulty: "L" },
      { title: "逆月", difficulty: "A" },
      { title: "九尾狐夜行", difficulty: "A" },
      { title: "残像ニ繋ガレタ追憶ノHIDEAWAY", difficulty: "A" },
      { title: "世界の果てに約束の凱歌を -ReUnion-", difficulty: "A" },
      { title: "千年ノ理", difficulty: "L" },
      { title: "表裏一体！？怪盗いいんちょの悩み♥", difficulty: "L" },
      { title: "≡+≡", difficulty: "L" },
      { title: "Lisa-RICCIA", difficulty: "L" },
      { title: "Regina vespaE", difficulty: "A" },
      { title: "ミュージック・アワー", difficulty: "L" },
    ],
  },
  "CHARGE": {
    "8-10": [
      { title: "ATOMIC AGE", difficulty: "A" },
      { title: "Miami Sunset Drive", difficulty: "A" },
      { title: "ロマンシングエスケープ", difficulty: "A" },
      { title: "獅子霞麗ノ舞", difficulty: "A" },
      { title: "真夏の花・真夏の夢", difficulty: "A" },
      { title: "Almace", difficulty: "A" },
      { title: "Arcana", difficulty: "A" },
      { title: "Arcanos", difficulty: "A" },
      { title: "Deep Sea Mystery", difficulty: "A" },
      { title: "Donkey Donk", difficulty: "A" },
      { title: "Everlasting Resort", difficulty: "A" },
      { title: "Galaxy Collapse", difficulty: "A" },
      { title: "Golden Palms", difficulty: "A" },
      { title: "Infinity Mirror", difficulty: "A" },
      { title: "Light Shine", difficulty: "A" },
      { title: "OUTER PLANETS", difficulty: "A" },
      { title: "Pink Rose", difficulty: "L" },
      { title: "RIDE ON THE LIGHT (HI GREAT MIX)", difficulty: "L" },
      { title: "Sunny Day Vibes", difficulty: "A" },
      { title: "The Best of Both Worlds", difficulty: "A" },
      { title: "Virus Funk", difficulty: "A" },
      { title: "ないないルーティン", difficulty: "A" },
      { title: "ラストセンチュリーメランコリック", difficulty: "A" },
      { title: "最強頂戴girl♡", difficulty: "A" },
      { title: "少女アリスと箱庭幻想コンチェルト", difficulty: "A" },
      { title: "新宝島", difficulty: "A" },
      { title: "流桜ノ門", difficulty: "A" },
    ],
    "11": [
      { title: "10000 MILES AWAY", difficulty: "A" },
      { title: "ABSOLUTE", difficulty: "L" },
      { title: "ABSOLUTE (kors k Remix)", difficulty: "A" },
      { title: "Acid Pumper", difficulty: "A" },
      { title: "ADAMANT", difficulty: "A" },
      { title: "CALL", difficulty: "L" },
      { title: "Chronos", difficulty: "A" },
      { title: "Clione", difficulty: "L" },
      { title: "Daily Lunch Special", difficulty: "A" },
      { title: "Dawn Saga", difficulty: "A" },
      { title: "Elisha", difficulty: "A" },
      { title: "Energy Drive", difficulty: "A" },
      { title: "Ergosphere", difficulty: "A" },
      { title: "Fiery Stallion", difficulty: "A" },
      { title: "GIGA RAID", difficulty: "A" },
      { title: "GIGANT", difficulty: "L" },
      { title: "Golden Palms", difficulty: "L" },
      { title: "Kailua", difficulty: "A" },
      { title: "MIRACLE MEETS", difficulty: "A" },
      { title: "Nocturnal 2097", difficulty: "A" },
      { title: "of the first magnitude", difficulty: "A" },
      { title: "Perfect Plan", difficulty: "A" },
      { title: "Psycho Sheep Riddim", difficulty: "L" },
      { title: "Rejection Girl", difficulty: "A" },
      { title: "ROCK女 feat. 大山愛未, Ken", difficulty: "A" },
      { title: "S!ck (Nhato Remix)", difficulty: "A" },
      { title: "Sakura Reflection", difficulty: "A" },
      { title: "Scars of FAUNA", difficulty: "A" },
      { title: "Souhait bleu", difficulty: "A" },
      { title: "Space In Time", difficulty: "A" },
      { title: "Star Trail", difficulty: "L" },
      { title: "THE BLACK KNIGHT", difficulty: "A" },
      { title: "Urban Constellations", difficulty: "A" },
      { title: "VALLIS-NERIA", difficulty: "A" },
      { title: "Wolf 1061", difficulty: "A" },
      { title: "XINOBIKILL", difficulty: "A" },
      { title: "Zenith", difficulty: "A" },
      { title: "鬼天", difficulty: "A" },
      { title: "乱膳の舞姫", difficulty: "A" },
      { title: "BattleRoyal", difficulty: "A" },
    ],
    "12": [
      { title: "ABSOLUTE EVIL", difficulty: "A" },
      { title: "Adularia", difficulty: "A" },
      { title: "Aftermath", difficulty: "A" },
      { title: "Almagest", difficulty: "A" },
      { title: "BEAT PRISONER", difficulty: "A" },
      { title: "BIGソムタム", difficulty: "A" },
      { title: "Carmina", difficulty: "A" },
      { title: "DIAMOND CROSSING", difficulty: "A" },
      { title: "DIVINE JUDGEMENT", difficulty: "A" },
      { title: "ECHIDNA", difficulty: "A" },
      { title: "Everlasting Message", difficulty: "A" },
      { title: "Hollywood Galaxy", difficulty: "A" },
      { title: "Ignis†Iræ", difficulty: "A" },
      { title: "LOCUS OF THE TRAVEL", difficulty: "A" },
      { title: "NOIXIA", difficulty: "A" },
      { title: "NZM", difficulty: "A" },
      { title: "Painful Fate", difficulty: "A" },
      { title: "Papilio ulysses", difficulty: "A" },
      { title: "PARADISE LOST", difficulty: "A" },
      { title: "Reflux", difficulty: "A" },
      { title: "REVOLVER", difficulty: "L" },
      { title: "Sinus Iridum", difficulty: "A" },
      { title: "Snakey Kung-fu", difficulty: "A" },
      { title: "Somnidiscotheque", difficulty: "A" },
      { title: "Steel Edge", difficulty: "A" },
      { title: "Timepiece phase II (CN Ver.)", difficulty: "A" },
      { title: "TITANS RETURN", difficulty: "L" },
      { title: "TOGAKUSHI", difficulty: "A" },
      { title: "Triple Cross", difficulty: "A" },
      { title: "TRIUMPH", difficulty: "A" },
      { title: "Umbral", difficulty: "L" },
      { title: "Unbelief", difficulty: "A" },
      { title: "Valanga", difficulty: "A" },
      { title: "ディスコルディア", difficulty: "A" },
      { title: "ミラージュ・レジデンス", difficulty: "L" },
      { title: "栄冠のカンパネラ", difficulty: "A" },
      { title: "海神", difficulty: "L" },
      { title: "共鳴遊戯の華", difficulty: "A" },
      { title: "蛇神", difficulty: "L" },
      { title: "新宝島", difficulty: "L" },
      { title: "深淵に捧ぐレクイエム", difficulty: "A" },
      { title: "真 地獄超特急 -HELL or HELL-", difficulty: "A" },
      { title: "神のシナリオ", difficulty: "A" },
      { title: "水鏡の異界", difficulty: "A" },
      { title: "摩天楼", difficulty: "A" },
      { title: "魔法のかくれんぼ", difficulty: "A" },
      { title: "龍王の霊廟(Mausoleum Of The Primal Dragon)", difficulty: "L" },
      { title: "烽火連天の刃", difficulty: "L" },
      { title: "禊", difficulty: "A" },
      { title: "chaplet -IIDX re:build-", difficulty: "A" },
    ],
  },
  "SCRATCH": {
    "8-10": [
      { title: "Spin the disc", difficulty: "A" },
      { title: "サヨナラ・ヘヴン", difficulty: "A" },
      { title: "Close my Eyes for Me", difficulty: "A" },
      { title: "Driver", difficulty: "A" },
      { title: "route 80s", difficulty: "A" },
      { title: "Somebody Like You", difficulty: "A" },
      { title: "250bpm", difficulty: "A" },
      { title: "5.1.1.", difficulty: "A" },
      { title: "bass 2 bass", difficulty: "A" },
      { title: "Buffalo", difficulty: "A" },
      { title: "Catch Me", difficulty: "A" },
      { title: "Do Back Burn", difficulty: "A" },
      { title: "Feedback", difficulty: "A" },
      { title: "HEARTACHE", difficulty: "A" },
      { title: "Hella Deep", difficulty: "A" },
      { title: "Midnight Drive", difficulty: "A" },
      { title: "NO LIMIT -オレ達に限界は無い-", difficulty: "A" },
      { title: "Non Stop Rock", difficulty: "A" },
      { title: "PIT A PAT", difficulty: "A" },
      { title: "Really Love", difficulty: "A" },
      { title: "rottel-da-sun", difficulty: "A" },
      { title: "Shamshir", difficulty: "A" },
      { title: "SPEED DEMON", difficulty: "A" },
      { title: "SWEET LAB", difficulty: "A" },
      { title: "Tripping Jumping", difficulty: "A" },
      { title: "Vibing! Shake it!", difficulty: "A" },
      { title: "WAR GAME", difficulty: "A" },
      { title: "オレはビートマニア！お前は何マニア？", difficulty: "A" },
      { title: "灼熱Beach Side Bunny (Masayoshi Iimori Remix)", difficulty: "A" },
      { title: "廿", difficulty: "A" },
    ],
    "11": [
      { title: "27th style", difficulty: "A" },
      { title: "Beat Juggling Mix", difficulty: "A" },
      { title: "Bounce Bounce Bounce", difficulty: "A" },
      { title: "CHECKING YOU OUT", difficulty: "A" },
      { title: "CODE:0", difficulty: "A" },
      { title: "Digitank System", difficulty: "A" },
      { title: "EXODUS SIGN", difficulty: "A" },
      { title: "Halfway of promise", difficulty: "A" },
      { title: "Hydrogen Blueback", difficulty: "L" },
      { title: "IDC feat.REVERBEE (Mo'Cuts Ver)", difficulty: "A" },
      { title: "Just a Little Smile", difficulty: "A" },
      { title: "naughty girl@Queen's Palace", difficulty: "L" },
      { title: "rough percussionythm", difficulty: "A" },
      { title: "Routing", difficulty: "A" },
      { title: "SAMURAI-Scramble", difficulty: "A" },
      { title: "Swarm Of Scarabs", difficulty: "A" },
      { title: "SWEETEST SAVAGE", difficulty: "A" },
      { title: "TRIP THE DEEP", difficulty: "A" },
      { title: "Uh-Oh", difficulty: "A" },
      { title: "VOLCANIC BIGBEAT", difficulty: "A" },
      { title: "Wonder Bullfighter", difficulty: "A" },
      { title: "カジノファイヤーことみちゃん", difficulty: "A" },
      { title: "とろぴかる倶楽部", difficulty: "A" },
      { title: "ベィスドロップ・フリークス", difficulty: "L" },
      { title: "ラクエン", difficulty: "A" },
      { title: "花冠 feat.Aikapin", difficulty: "A" },
    ],
    "12": [
      { title: "199024club -Re:BounceKiller-", difficulty: "A" },
      { title: "Be quiet", difficulty: "L" },
      { title: "BLACK.by X-Cross Fade", difficulty: "A" },
      { title: "BLUE MIRAGE", difficulty: "A" },
      { title: "Caterpillar", difficulty: "A" },
      { title: "Cult Invitation", difficulty: "A" },
      { title: "Don't believe the hype", difficulty: "A" },
      { title: "Double Dribble", difficulty: "A" },
      { title: "GAME ON", difficulty: "A" },
      { title: "Level 2", difficulty: "A" },
      { title: "Level 3", difficulty: "A" },
      { title: "Level 4", difficulty: "A" },
      { title: "Level 5", difficulty: "A" },
      { title: "Level One", difficulty: "A" },
      { title: "Lords Of The Roundtable", difficulty: "A" },
      { title: "MAD ATTACK", difficulty: "L" },
      { title: "Miracle 5ympho X", difficulty: "L" },
      { title: "Peaktime Booster", difficulty: "A" },
      { title: "Plan 8", difficulty: "A" },
      { title: "Purple Perplex", difficulty: "A" },
      { title: "RAGE feat.H14 of LEONAIR", difficulty: "A" },
      { title: "Red. by Full Metal Jacket", difficulty: "A" },
      { title: "Red. by Jack Trance", difficulty: "A" },
      { title: "SAMURAI-Scramble", difficulty: "L" },
      { title: "SAY BAY", difficulty: "A" },
      { title: "SCREW // owo // SCREW", difficulty: "A" },
      { title: "Skratch Education Lv-1", difficulty: "A" },
      { title: "Snake Stick", difficulty: "A" },
      { title: "The Chase", difficulty: "A" },
      { title: "Watch Out Pt.2", difficulty: "A" },
      { title: "WHA", difficulty: "A" },
      { title: "Xperanza", difficulty: "A" },
      { title: "バッド・スイーツ、バッド・ドリーム", difficulty: "A" },
      { title: "灼熱 Lost Summer Dayz", difficulty: "A" },
      { title: "灼熱 Pt.2 Long Train Running", difficulty: "A" },
      { title: "灼熱Beach Side Bunny", difficulty: "A" },
      { title: "灼熱Beach Side Bunny (かめりあ's \"Summertime D'n'B\" Remix)", difficulty: "A" },
      { title: "雪上断火", difficulty: "A" },
      { title: "焱影", difficulty: "A" },
      { title: "Makin' It", difficulty: "A" },
    ],
  },
  "SOF-LAN": {
    "8-10": [
      { title: "empathy", difficulty: "A" },
      { title: "Voltage (feat. Hidemaru)", difficulty: "A" },
      { title: "2hot2eat", difficulty: "A" },
      { title: "era (nostalmix)", difficulty: "A" },
      { title: "era (step mix)", difficulty: "A" },
      { title: "mind the gap", difficulty: "A" },
      { title: "Agnus Dei", difficulty: "A" },
      { title: "fun", difficulty: "A" },
      { title: "GRADIUS -FULL SPEED-", difficulty: "A" },
      { title: "op.31 叙情", difficulty: "A" },
      { title: "PARANOIA survivor MAX", difficulty: "A" },
      { title: "Surf on the Light", difficulty: "A" },
      { title: "罪過の聖堂", difficulty: "A" },
    ],
    "11": [
      { title: "(This Is Not) The Angels", difficulty: "A" },
      { title: "Ah Hah Yeah", difficulty: "A" },
      { title: "D", difficulty: "A" },
      { title: "four pieces of heaven", difficulty: "A" },
      { title: "FUTURE is Dead", difficulty: "A" },
      { title: "Linus", difficulty: "A" },
      { title: "nostos", difficulty: "A" },
      { title: "Onyx", difficulty: "A" },
      { title: "SABER WING", difficulty: "A" },
      { title: "T.R.O.L.L.", difficulty: "A" },
      { title: "Theory", difficulty: "A" },
    ],
    "12": [
      { title: "Concertino in Blue", difficulty: "A" },
      { title: "DAY DREAM", difficulty: "A" },
      { title: "DropZ-Line-", difficulty: "A" },
      { title: "Fascination MAXX", difficulty: "A" },
      { title: "Glitch N Ride", difficulty: "A" },
      { title: "ICARUS", difficulty: "L" },
      { title: "JOMANDA", difficulty: "A" },
      { title: "n/a", difficulty: "A" },
      { title: "New Castle Legions", difficulty: "A" },
      { title: "PARANOiA ～HADES～", difficulty: "A" },
      { title: "POSSESSION", difficulty: "A" },
      { title: "ruin of opals", difficulty: "A" },
      { title: "Silver Bullet", difficulty: "A" },
      { title: "VØID", difficulty: "A" },
      { title: "Y&Co. is dead or alive", difficulty: "A" },
      { title: "ピアノ協奏曲第１番”蠍火”", difficulty: "A" },
      { title: "ピアノ独奏無言歌 \"灰燼\"", difficulty: "A" },
      { title: "ワルツ第17番 ト短調”大犬のワルツ”", difficulty: "A" },
      { title: "音楽", difficulty: "A" },
      { title: "桜", difficulty: "A" },
      { title: "聖人の塔", difficulty: "A" },
      { title: "冥", difficulty: "A" },
      { title: "恋愛＝精度×認識力", difficulty: "A" },
      { title: "惑星鉄道", difficulty: "A" },
    ],
  },
};